### ISSUE TITLE
Some (?) libraries shipped as CommonJS modules refuse to build with default rollup configs

### ISSUE THREAD

**Issue by mwozniczak** [yamafaktory/babel-react-rollup-starter#29]
I wanted to use this starter as a jumping off point for learning the [react-diagrams](https://github.com/projectstorm/react-diagrams/) library. Unfortunately, it appears that it being a commonJS module is breaking the build resulting with either `'CanvasWidget' is not exported by node_modules\storm-react-diagrams\src\main.js` or `'default' is not exported by node_modules\storm-react-diagrams\src\main.js` depending on how I try to import it. I suspect some fiddling with `cjs`'s settings would resolve that, but so far my attempts to do so have failed. Will re-attempt tomorrow.

I've already opened [an issue](https://github.com/projectstorm/react-diagrams/issues/6) with the library in question, but perhaps it might be worthwhile to use it as a test-case for ensuring that libraries shipped in that way can be imported easily?

**Comment by yamafaktory** [comment]
@mwozniczak I totally get your point but this issue is definitely out of the scope of this simple starter project. The issue you are describing seems to be related to https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module. The project itself can't (and won't) fix it as *rollup-plugin-commonjs* doesn't always generate named exports from the CommonJS code. _De facto_, using it as a test case will not help, potentially any CommonJS library can break it. Please try to fix it by checking the aforementioned solution.

**Comment by mwozniczak** [comment]
I wouldn't post an issue here if it were as easily solvable with a link that is provided immediately after that error ;) I _suspect_ it was caused by those requires within requires in that module's `main.js`, but yesterday I ran out of time to confirm.

To your argument, I offer a counterpoint: there's a lot of libs on NPM that have not yet migrated to the ES6 modules syntax, and it would be nice if they could be easily used without any hassle. I've provided one such example mostly for ease of investigation.

Anyway, I _think_ I've solved it in a rollup config for one of my previous projects, but would have to verify. If I did, would you be interested in a PR for that?

**Comment by yamafaktory** [comment]
@mwozniczak of course, feel free to provide a PR for that 👍. Your counterpoint is absolutely going in the same direction as my response, _rollup-plugin-commonjs_ doesn't always generate named exports from the CommonJS code and I totally agree that there's a lot of non-ES6 modules on npm. My point was that this small project was initially though as a simple starter. I don't think that you can provide a universal fix for that issue, that's why I was pointing to the Rollup's wiki 😄.
